name: Do Something That Needs Scheduled

on:
  repository_dispatch:
    types: do-something

jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: g++ hello-world.cpp 
    - name: run-test
      run: ./a.out
